### ISSUE TITLE
Types do not align in the example and compilation fails

### ISSUE THREAD

**Issue by ceecer1** [gbogard/cats-mtl-talk#3]
Based on:
https://guillaumebogard.dev/posts/functional-error-handling/

With following dependencies version,
libraryDependencies ++= Seq(
    "org.typelevel" %% "cats-effect" % "3.1.1" withSources() withJavadoc(),
    "org.typelevel" %% "cats-mtl" % "1.2.0" withSources() withJavadoc(),
    "org.typelevel" %% "munit-cats-effect-3" % "1.0.3" % Test
)

Hi @gbogard The below method illustrated in the example does not compile since 'handleWith' and 'recoverWith' are both expected to return F[User] but not F[Unit]. 

If you could suggest a fix, this is highly appreciated. Thank you.

  ```
def authenticateAndHandle[F[_]](username: String, password: String)(
          implicit ME: MonadError[F, Throwable],
          H: Handle[F, AuthenticationError],
          // `Sync` is the type class that describes the ability to suspend side effects
          // `IO` provides a concrete instance of Sync
          Sync: Sync[F]
      ) =
          authenticate[F](username, password)
          .handleWith[AuthenticationError] ({
              //handle business errors
              case WrongPassword => Sync.delay { 
                  println(s"Wrong password")
              }
              case WrongUsername => Sync.delay { println("Wrong username") }
              case e: AuthenticationError => 
                  Sync.delay { 
                      println("Auth error")
                  }
          })
          //Handle technical errors
          .recoverWith({
              case e: Throwable => Sync.delay {
                  println(s"Something went wrong terribly ${e.getMessage()}")
              }
          })

    override def run(args: List[String]): IO[ExitCode] = {
        //interpreting the program
        type F[A] = EitherT[IO, AuthenticationError, A]
        for {
            _ <- authenticateAndHandle[F]("john.doe", "123").value
            // _ <- authenticate[F]("john.doe", "123").value
        } yield ExitCode.Success
        
```

**Comment by gbogard** [comment]
Hi @ceecer1, thank you for opening an issue! 
I'll take a look later tonight

**Comment by gbogard** [comment]
Hi @ceecer1. I've updated the examples in the `example` folder, and [in the article](http://localhost:1313/posts/functional-error-handling/#final-examples-and-conclusion)

Thank you again for your feedback
